;TITLE PGM4_1: ECHO PROGRAM
.MODEL SMALL
.STACK 100H
.CODE

MAIN PROC
    ;DISPLAY PROMT
    MOV AH, 2   ;DISPLAY CHARACTER FUNCTION
    MOV DL, "?" ;CHARACTER IS "?"
    INT 21h     ;DISPLAYING IT
    
    ;INPUT A CHARACTER
    MOV AH, 1   ;READ CHARACTER FUNCTION
    INT 21H     ;CHARACTER IN AL
    MOV BL, AL  ;SAVE IT IN BL
    
    ;GO TO A NEW LINE
    MOV AH, 2   ;DISPLAY CHARACTER FUNCTION
    MOV DL, 0DH ;CARRIAGE RETURN
    INT 21H     ;EXECUTE CARRIAGE RETURN
    MOV DL, 0AH ;LINE FEED
    INT 21H     ;EXECUTE LINE FEED
    
    ;DISPLAY CHARACTER
    MOV DL, BL  ;RETRIEVE CHARACTER
    INT 21H     ;DISPLAY IT 
    
    ;RETURN TO DOS
    MOV AH, 4CH ;DOS EXIT FUNCTION
    INT 21H     ;EXIT DOS
    
    MAIN ENDP
END MAIN